// Copyright 2022
// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FLTImagePreviewApi.
NSObject<FlutterMessageCodec> *FLTImagePreviewApiGetCodec(void);

@protocol FLTImagePreviewApi
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)create:(FlutterError *_Nullable *_Nonnull)error;
- (void)connect:(NSNumber *)textureId  :(NSArray<NSNumber *> *)filters  :(NSString *)context error:(FlutterError *_Nullable *_Nonnull)error;
- (void)disconnect:(NSNumber *)textureId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setSource:(NSNumber *)textureId  asset:(NSString *)path error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setSource:(NSNumber *)textureId  path:(NSString *)path error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setSource:(NSNumber *)textureId  data:(FlutterStandardTypedData *)data error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setOutput:(NSNumber *)textureId  :(NSArray<NSNumber *> *)value error:(FlutterError *_Nullable *_Nonnull)error;
- (void)dispose:(NSNumber *)textureId error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTImagePreviewApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTImagePreviewApi> *_Nullable api);

/// The codec used by FLTVideoPreviewApi.
NSObject<FlutterMessageCodec> *FLTVideoPreviewApiGetCodec(void);

@protocol FLTVideoPreviewApi
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)create:(FlutterError *_Nullable *_Nonnull)error;
- (void)connect:(NSNumber *)textureId  :(NSArray<NSNumber *> *)filters  :(NSString *)context error:(FlutterError *_Nullable *_Nonnull)error;
- (void)disconnect:(NSNumber *)textureId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setSource:(NSNumber *)textureId  asset:(NSString *)path error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setSource:(NSNumber *)textureId  path:(NSString *)path error:(FlutterError *_Nullable *_Nonnull)error;
- (void)resume:(NSNumber *)textureId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)pause:(NSNumber *)textureId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)dispose:(NSNumber *)textureId error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTVideoPreviewApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTVideoPreviewApi> *_Nullable api);

NS_ASSUME_NONNULL_END
