const Map<String, String> kNames = {
  'Accordion Fold Transition': 'CIAccordionFoldTransition',
  'Addition': 'CIAdditionCompositing',
  'Affine Clamp': 'CIAffineClamp',
  'Affine Tile': 'CIAffineTile',
  'Affine Transform': 'CIAffineTransform',
  'Area Average': 'CIAreaAverage',
  'Area Histogram': 'CIAreaHistogram',
  'Area Logarithmic Histogram': 'CIAreaLogarithmicHistogram',
  'Area Maximum': 'CIAreaMaximum',
  'Area Maximum Alpha': 'CIAreaMaximumAlpha',
  'Area Minimum': 'CIAreaMinimum',
  'Area Minimum Alpha': 'CIAreaMinimumAlpha',
  'Area Min and Max': 'CIAreaMinMax',
  'Area Min and Max Red': 'CIAreaMinMaxRed',
  'Attributed Text Image Generator': 'CIAttributedTextImageGenerator',
  'Aztec Code Generator': 'CIAztecCodeGenerator',
  'Barcode Generator': 'CIBarcodeGenerator',
  'Bars Swipe Transition': 'CIBarsSwipeTransition',
  'Bicubic Scale Transform': 'CIBicubicScaleTransform',
  'Blend With Alpha Mask': 'CIBlendWithAlphaMask',
  'Blend With Blue Mask': 'CIBlendWithBlueMask',
  'Blend With Mask': 'CIBlendWithMask',
  'Blend With Red Mask': 'CIBlendWithRedMask',
  'Bloom': 'CIBloom',
  'Bokeh Blur': 'CIBokehBlur',
  'Box Blur': 'CIBoxBlur',
  'Bump Distortion': 'CIBumpDistortion',
  'Bump Distortion Linear': 'CIBumpDistortionLinear',
  'Lens Correction for AVC': 'CICameraCalibrationLensCorrection',
  'Checkerboard': 'CICheckerboardGenerator',
  'Circle Splash Distortion': 'CICircleSplashDistortion',
  'Circular Screen': 'CICircularScreen',
  'Circular Wrap Distortion': 'CICircularWrap',
  'Clamp': 'CIClamp',
  'CMYK Halftone': 'CICMYKHalftone',
  'Code 128 Barcode Generator': 'CICode128BarcodeGenerator',
  'Color Absolute Difference': 'CIColorAbsoluteDifference',
  'Color Blend Mode': 'CIColorBlendMode',
  'Color Burn Blend Mode': 'CIColorBurnBlendMode',
  'Color Clamp': 'CIColorClamp',
  'Color Controls': 'CIColorControls',
  'Color Cross Polynomial': 'CIColorCrossPolynomial',
  'Color Cube': 'CIColorCube',
  'Color Cubes Mixed With Mask': 'CIColorCubesMixedWithMask',
  'Color Cube with ColorSpace': 'CIColorCubeWithColorSpace',
  'Color Curves': 'CIColorCurves',
  'Color Dodge Blend Mode': 'CIColorDodgeBlendMode',
  'Color Invert': 'CIColorInvert',
  'Color Map': 'CIColorMap',
  'Color Matrix': 'CIColorMatrix',
  'Color Monochrome': 'CIColorMonochrome',
  'Color Polynomial': 'CIColorPolynomial',
  'Color Posterize': 'CIColorPosterize',
  'Color Threshold': 'CIColorThreshold',
  'Color Threshold Otsu': 'CIColorThresholdOtsu',
  'Column Average': 'CIColumnAverage',
  'Comic Effect': 'CIComicEffect',
  'Constant Color': 'CIConstantColorGenerator',
  'Convert Lab to RGB': 'CIConvertLabToRGB',
  'Convert RGB to Lab': 'CIConvertRGBtoLab',
  '3 by 3 Convolution': 'CIConvolution3X3',
  '5 by 5 Convolution': 'CIConvolution5X5',
  '7 by 7 Convolution': 'CIConvolution7X7',
  'Horizontal 9 Convolution': 'CIConvolution9Horizontal',
  'Vertical 9 Convolution': 'CIConvolution9Vertical',
  '3 by 3 RGB Convolution': 'CIConvolutionRGB3X3',
  '5 by 5 RGB Convolution': 'CIConvolutionRGB5X5',
  '7 by 7 RGB Convolution': 'CIConvolutionRGB7X7',
  'Horizontal 9 RGB Convolution': 'CIConvolutionRGB9Horizontal',
  'Vertical 9 RGB Convolution': 'CIConvolutionRGB9Vertical',
  'Copy Machine': 'CICopyMachineTransition',
  'CoreML Model Filter': 'CICoreMLModelFilter',
  'Crop': 'CICrop',
  'Crystallize': 'CICrystallize',
  'Darken Blend Mode': 'CIDarkenBlendMode',
  'Depth Blur Effect': 'CIDepthBlurEffect',
  'Depth of Field': 'CIDepthOfField',
  'Depth To Disparity': 'CIDepthToDisparity',
  'Difference Blend Mode': 'CIDifferenceBlendMode',
  'Disc Blur': 'CIDiscBlur',
  'Disintegrate With Mask': 'CIDisintegrateWithMaskTransition',
  'Disparity To Depth': 'CIDisparityToDepth',
  'Displacement Distortion': 'CIDisplacementDistortion',
  'Dissolve': 'CIDissolveTransition',
  'Dither': 'CIDither',
  'Divide Blend Mode': 'CIDivideBlendMode',
  'Document Enhancer': 'CIDocumentEnhancer',
  'Dot Screen': 'CIDotScreen',
  'Droste': 'CIDroste',
  'Edge Preserve Upsample Filter': 'CIEdgePreserveUpsampleFilter',
  'Edges': 'CIEdges',
  'Edge Work': 'CIEdgeWork',
  'Eightfold Reflected Tile': 'CIEightfoldReflectedTile',
  'Exclusion Blend Mode': 'CIExclusionBlendMode',
  'Exposure Adjust': 'CIExposureAdjust',
  'False Color': 'CIFalseColor',
  'Flash': 'CIFlashTransition',
  'Fourfold Reflected Tile': 'CIFourfoldReflectedTile',
  'Fourfold Rotated Tile': 'CIFourfoldRotatedTile',
  'Fourfold Translated Tile': 'CIFourfoldTranslatedTile',
  'Gabor Gradients': 'CIGaborGradients',
  'Gamma Adjust': 'CIGammaAdjust',
  'Gaussian Blur': 'CIGaussianBlur',
  'Gaussian Gradient': 'CIGaussianGradient',
  'Glass Distortion': 'CIGlassDistortion',
  'Glass Lozenge': 'CIGlassLozenge',
  'Glide Reflected Tile': 'CIGlideReflectedTile',
  'Gloom': 'CIGloom',
  'Guided Filter': 'CIGuidedFilter',
  'Hard Light Blend Mode': 'CIHardLightBlendMode',
  'Hatched Screen': 'CIHatchedScreen',
  'Height Field From Mask': 'CIHeightFieldFromMask',
  'Hexagonal Pixelate': 'CIHexagonalPixellate',
  'Highlight and Shadow Adjust': 'CIHighlightShadowAdjust',
  'Histogram Display': 'CIHistogramDisplayFilter',
  'Hole Distortion': 'CIHoleDistortion',
  'Hue Adjust': 'CIHueAdjust',
  'Hue Blend Mode': 'CIHueBlendMode',
  'Hue/Saturation/Value Gradient': 'CIHueSaturationValueGradient',
  'Kaleidoscope': 'CIKaleidoscope',
  'Combined Keystone Correction': 'CIKeystoneCorrectionCombined',
  'Horizontal Keystone Correction': 'CIKeystoneCorrectionHorizontal',
  'Vertical Keystone Correction': 'CIKeystoneCorrectionVertical',
  'KMeans': 'CIKMeans',
  'Lab ∆E': 'CILabDeltaE',
  'Lanczos Scale Transform': 'CILanczosScaleTransform',
  'Lenticular Halo': 'CILenticularHaloGenerator',
  'Lighten Blend Mode': 'CILightenBlendMode',
  'Light Tunnel Distortion': 'CILightTunnel',
  'Linear Burn Blend Mode': 'CILinearBurnBlendMode',
  'Linear Dodge Blend Mode': 'CILinearDodgeBlendMode',
  'Linear Gradient': 'CILinearGradient',
  'Linear Light Blend Mode': 'CILinearLightBlendMode',
  'Linear to sRGB Tone Curve': 'CILinearToSRGBToneCurve',
  'Line Overlay': 'CILineOverlay',
  'Line Screen': 'CILineScreen',
  'Luminosity Blend Mode': 'CILuminosityBlendMode',
  'Masked Variable Blur': 'CIMaskedVariableBlur',
  'Mask to Alpha': 'CIMaskToAlpha',
  'Maximum Component': 'CIMaximumComponent',
  'Maximum': 'CIMaximumCompositing',
  'Median': 'CIMedianFilter',
  'Mesh Generator': 'CIMeshGenerator',
  'Minimum Component': 'CIMinimumComponent',
  'Minimum': 'CIMinimumCompositing',
  'Mix': 'CIMix',
  'Mod': 'CIModTransition',
  'Morphology Gradient': 'CIMorphologyGradient',
  'Morphology Maximum': 'CIMorphologyMaximum',
  'Morphology Minimum': 'CIMorphologyMinimum',
  'Morphology Rectangle Maximum': 'CIMorphologyRectangleMaximum',
  'Morphology Rectangle Minimum': 'CIMorphologyRectangleMinimum',
  'Motion Blur': 'CIMotionBlur',
  'Multiply Blend Mode': 'CIMultiplyBlendMode',
  'Multiply': 'CIMultiplyCompositing',
  'Nine Part Stretched': 'CINinePartStretched',
  'Nine Part Tiled': 'CINinePartTiled',
  'Noise Reduction': 'CINoiseReduction',
  'Op Tile': 'CIOpTile',
  'Overlay Blend Mode': 'CIOverlayBlendMode',
  'Page Curl': 'CIPageCurlTransition',
  'Page Curl With Shadow': 'CIPageCurlWithShadowTransition',
  'Palette Centroid': 'CIPaletteCentroid',
  'Palettize': 'CIPalettize',
  'Parallelogram Tile': 'CIParallelogramTile',
  'PDF417 Barcode Generator': 'CIPDF417BarcodeGenerator',
  'Person Segmentation': 'CIPersonSegmentation',
  'Perspective Correction': 'CIPerspectiveCorrection',
  'Perspective Rotate': 'CIPerspectiveRotate',
  'Perspective Tile': 'CIPerspectiveTile',
  'Perspective Transform': 'CIPerspectiveTransform',
  'Perspective Transform with Extent': 'CIPerspectiveTransformWithExtent',
  'Photo Effect Chrome': 'CIPhotoEffectChrome',
  'Photo Effect Fade': 'CIPhotoEffectFade',
  'Photo Effect Instant': 'CIPhotoEffectInstant',
  'Photo Effect Mono': 'CIPhotoEffectMono',
  'Photo Effect Noir': 'CIPhotoEffectNoir',
  'Photo Effect Process': 'CIPhotoEffectProcess',
  'Photo Effect Tonal': 'CIPhotoEffectTonal',
  'Photo Effect Transfer': 'CIPhotoEffectTransfer',
  'Pinch Distortion': 'CIPinchDistortion',
  'Pin Light Blend Mode': 'CIPinLightBlendMode',
  'Pixelate': 'CIPixellate',
  'Pointillize': 'CIPointillize',
  'QR Code Generator': 'CIQRCodeGenerator',
  'Radial Gradient': 'CIRadialGradient',
  'Random Generator': 'CIRandomGenerator',
  'Ripple': 'CIRippleTransition',
  'Rounded Rectangle Generator': 'CIRoundedRectangleGenerator',
  'Row Average': 'CIRowAverage',
  'Saliency Map Filter': 'CISaliencyMapFilter',
  'Sample Nearest': 'CISampleNearest',
  'Saturation Blend Mode': 'CISaturationBlendMode',
  'Screen Blend Mode': 'CIScreenBlendMode',
  'Sepia Tone': 'CISepiaTone',
  'Shaded Material': 'CIShadedMaterial',
  'Sharpen Luminance': 'CISharpenLuminance',
  'Sixfold Reflected Tile': 'CISixfoldReflectedTile',
  'Sixfold Rotated Tile': 'CISixfoldRotatedTile',
  'Smooth Linear Gradient': 'CISmoothLinearGradient',
  'Soft Light Blend Mode': 'CISoftLightBlendMode',
  'Source Atop': 'CISourceAtopCompositing',
  'Source In': 'CISourceInCompositing',
  'Source Out': 'CISourceOutCompositing',
  'Source Over': 'CISourceOverCompositing',
  'Spot Color': 'CISpotColor',
  'Spot Light': 'CISpotLight',
  'sRGB Tone Curve to Linear': 'CISRGBToneCurveToLinear',
  'Star Shine': 'CIStarShineGenerator',
  'Straighten': 'CIStraightenFilter',
  'Stretch Crop': 'CIStretchCrop',
  'Stripes': 'CIStripesGenerator',
  'Subtract Blend Mode': 'CISubtractBlendMode',
  'Sunbeams': 'CISunbeamsGenerator',
  'Swipe': 'CISwipeTransition',
  'Temperature and Tint': 'CITemperatureAndTint',
  'Text Image Generator': 'CITextImageGenerator',
  'Thermal': 'CIThermal',
  'Tone Curve': 'CIToneCurve',
  'Torus Lens Distortion': 'CITorusLensDistortion',
  'Triangle Kaleidoscope': 'CITriangleKaleidoscope',
  'Triangle Tile': 'CITriangleTile',
  'Twelvefold Reflected Tile': 'CITwelvefoldReflectedTile',
  'Twirl Distortion': 'CITwirlDistortion',
  'Unsharp Mask': 'CIUnsharpMask',
  'Vibrance': 'CIVibrance',
  'Vignette': 'CIVignette',
  'Vignette Effect': 'CIVignetteEffect',
  'Vivid Light Blend Mode': 'CIVividLightBlendMode',
  'Vortex Distortion': 'CIVortexDistortion',
  'White Point Adjust': 'CIWhitePointAdjust',
  'X-Ray': 'CIXRay',
  'Zoom Blur': 'CIZoomBlur'
};
