name: Build and Deploy Flutter application
on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]

jobs:
  analyze_code:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Downloading sources
      - uses: subosito/flutter-action@v2
        name: Preparing Flutter SDK
        with:
          flutter-version: '3.13.6'
          channel: 'stable'
      - name: Analyze
        run: flutter analyze
      - name: Format
        run: |
          dart format --set-exit-if-changed lib
          dart format --set-exit-if-changed test